using System;
using System.Linq;
using Xunit;

namespace Kuery.Tests.Npgsql
{
    public class EqualsTest : IClassFixture<NpgsqlFixture>
    {
        readonly NpgsqlFixture fixture;

        public EqualsTest(NpgsqlFixture fixture)
        {
            this.fixture = fixture;
        }

        public abstract class TestObjBase<T>
        {
            [AutoIncrement, PrimaryKey]
            public int Id { get; set; }

            public T Data { get; set; }

            public DateTime Date { get; set; }
        }

        public class TestObjString : TestObjBase<string> { }

        void CreateTestTable(global::Npgsql.NpgsqlConnection connection)
        {
            connection.DropTable(nameof(TestObjString));

            using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = $@"
                    create table ""{nameof(TestObjString)}"" (
                        ""{nameof(TestObjString.Id)}"" integer primary key generated by default as identity,
                        ""{nameof(TestObjString.Data)}"" varchar(50) null,
                        ""{nameof(TestObjString.Date)}"" timestamp null
                    );";
                cmd.ExecuteNonQuery();
            }
        }

        [Fact]
        public void CanCompareAnyField()
        {
            var n = 20;
            var cq = from i in Enumerable.Range(1, n)
                     select new TestObjString
                     {
                         Data = Convert.ToString(i),
                         Date = new DateTime(2013, 1, i)
                     };
            using var db = fixture.OpenNewConnection();
            CreateTestTable(db);
            db.InsertAll(cq);

            var results = db.Table<TestObjString>().Where(o => o.Data.Equals("10"));
            Assert.Equal(1, results.Count());
            Assert.Equal("10", results.FirstOrDefault().Data);

            results = db.Table<TestObjString>().Where(o => o.Id.Equals(10));
            Assert.Equal(1, results.Count());
            Assert.Equal("10", results.FirstOrDefault().Data);

            var date = new DateTime(2013, 1, 10);
            results = db.Table<TestObjString>().Where(o => o.Date.Equals(date));
            Assert.Equal(1, results.Count());
            Assert.Equal("10", results.FirstOrDefault().Data);
        }
    }
}
